name: SellChest
version: ${pluginVersion}
main: net.tonimatasdev.sellchest.SellChest
api-version: 1.13
authors: [TonimatasDEV]
description: Sell chest

commands:
  sellchest:
    permission: sellchest.admin
    description: Primary command of SellChest plugin.

permissions:
  sellchest.*:
    description: All permissions of SellChest
    children:
      - sellchest.version

  sellchest.version:
    description: Show the plugin version.